image: registry.gitlab.frielforreal.com/friel/haskellstack:latest

cache:
  untracked: true

stages:
  - build

build:
  stage: build
  script:
    - ls -laR .
    - stack build
    - ls -laR .
    - git ls-files --others --exclude-standard