resolver: lts-7.9

packages:
- location: .
- location:
    git: https://github.com/aelve/stache-plus
    commit: e8e7967d561148167eb1fe4112c6ad0e091490ab
  extra-dep: true

extra-deps:
- cmark-sections-0.1.0.2
- http-client-0.5.1
- edit-distance-vector-1.0.0.4
- patches-vector-0.1.5.4
- fmt-0.0.0.4
