resolver: lts-6.14

packages:
- location: .
- location:
    git: https://github.com/aelve/stache-plus
    commit: a12f7edf9c034a01d5da466b212b3f9c0253b1f4
  extra-dep: true

extra-deps:
- cmark-highlight-0.2.0.0
- cmark-sections-0.1.0.2
- friendly-time-0.4
- ilist-0.2.0.0
- text-all-0.3.0.1
- text-show-3.3
- megaparsec-5.0.1
- http-client-0.5.1
- generic-deriving-1.10.7
- webdriver-0.8.4

flags:
  generic-deriving:
    base-4-9: false
  text-show:
    base-4-9: false
    template-haskell-2-11: false
    new-functor-classes: false
